"""Combination of all augmenters, related classes and related functions."""

from __future__ import annotations

import importlib
from abc import abstractmethod
from collections.abc import Callable


def abstractproperty(func: Callable[..., object]) -> property:
    return property(abstractmethod(func))

_SUBMODULE_NAMES = [
    "arithmetic",
    "artistic",
    "base",
    "blend",
    "blur",
    "color",
    "collections",
    "contrast",
    "convolutional",
    "debug",
    "edges",
    "experimental",
    "flip",
    "geometric",
    "imgcorruptlike",
    "meta",
    "mix",
    "overlay",
    "pillike",
    "pooling",
    "segmentation",
    "size",
    "weather",
]

_ATTR_TO_MODULE: dict[str, str] = {}


def __getattr__(name: str) -> object:
    if name in _SUBMODULE_NAMES:
        module = importlib.import_module(f"{__name__}.{name}")
        globals()[name] = module
        return module

    module_name = _ATTR_TO_MODULE.get(name)
    if module_name is not None:
        module = importlib.import_module(f"{__name__}.{module_name}")
        value = getattr(module, name)
        globals()[name] = value
        return value

    for submodule_name in _SUBMODULE_NAMES:
        module = importlib.import_module(f"{__name__}.{submodule_name}")
        exports = getattr(module, "__all__", None)
        if exports is None:
            exports = [attr for attr in dir(module) if not attr.startswith("_")]
        for attr in exports:
            _ATTR_TO_MODULE.setdefault(attr, submodule_name)
        if hasattr(module, name):
            value = getattr(module, name)
            globals()[name] = value
            return value

    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")


def __dir__() -> list[str]:
    # Keep this cheap: show current globals plus known submodules.
    return sorted(set(globals().keys()) | set(_SUBMODULE_NAMES))

__all__ = [
    "ABCMeta",
    "Add",
    "AddElementwise",
    "AddToBrightness",
    "AddToHue",
    "AddToHueAndSaturation",
    "AddToSaturation",
    "AdditiveGaussianNoise",
    "AdditiveLaplaceNoise",
    "AdditivePoissonNoise",
    "Affine",
    "AffineCv2",
    "AllChannelsCLAHE",
    "AllChannelsHistogramEqualization",
    "AssertLambda",
    "AssertShape",
    "Augmenter",
    "AverageBlur",
    "AveragePooling",
    "Batch",
    "BilateralBlur",
    "BlendAlpha",
    "BlendAlphaBoundingBoxes",
    "BlendAlphaCheckerboard",
    "BlendAlphaElementwise",
    "BlendAlphaFrequencyNoise",
    "BlendAlphaHorizontalLinearGradient",
    "BlendAlphaMask",
    "BlendAlphaRegularGrid",
    "BlendAlphaSegMapClassIds",
    "BlendAlphaSimplexNoise",
    "BlendAlphaSomeColors",
    "BlendAlphaVerticalLinearGradient",
    "BoundingBoxesMaskGen",
    "CLAHE",
    "CSPACE_ALL",
    "CSPACE_BGR",
    "CSPACE_CIE",
    "CSPACE_GRAY",
    "CSPACE_HLS",
    "CSPACE_HSV",
    "CSPACE_Lab",
    "CSPACE_Luv",
    "CSPACE_RGB",
    "CSPACE_YCrCb",
    "CSPACE_YUV",
    "Canny",
    "Cartoon",
    "CenterCropToAspectRatio",
    "CenterCropToFixedSize",
    "CenterCropToMultiplesOf",
    "CenterCropToPowersOf",
    "CenterCropToSquare",
    "CenterPadToAspectRatio",
    "CenterPadToFixedSize",
    "CenterPadToMultiplesOf",
    "CenterPadToPowersOf",
    "CenterPadToSquare",
    "ChangeColorTemperature",
    "ChangeColorspace",
    "ChannelShuffle",
    "CheckerboardMaskGen",
    "ClipCBAsToImagePlanes",
    "CloudLayer",
    "Clouds",
    "CoarseDropout",
    "CoarsePepper",
    "CoarseSalt",
    "CoarseSaltAndPepper",
    "Convolve",
    "Crop",
    "CropAndPad",
    "CropToAspectRatio",
    "CropToFixedSize",
    "CropToMultiplesOf",
    "CropToPowersOf",
    "CropToSquare",
    "Cutout",
    "DirectedEdgeDetect",
    "Dropout",
    "Dropout2d",
    "DropoutPointsSampler",
    "EdgeDetect",
    "ElasticTransformation",
    "Emboss",
    "FastSnowyLandscape",
    "Fliplr",
    "Flipud",
    "Fog",
    "GammaContrast",
    "GaussianBlur",
    "Grayscale",
    "GridDistortion",
    "HistogramEqualization",
    "HorizontalFlip",
    "HorizontalLinearGradientMaskGen",
    "IBatchwiseMaskGenerator",
    "IBinaryImageColorizer",
    "IPointsSampler",
    "Identity",
    "ImpulseNoise",
    "InColorspace",
    "Invert",
    "InvertMaskGen",
    "Jigsaw",
    "JpegCompression",
    "KMeansColorQuantization",
    "KeepSizeByResize",
    "Lambda",
    "LinearContrast",
    "LogContrast",
    "MaxPooling",
    "MeanShiftBlur",
    "MedianBlur",
    "MedianPooling",
    "MinPooling",
    "MotionBlur",
    "Multiply",
    "MultiplyAndAddToBrightness",
    "MultiplyBrightness",
    "MultiplyElementwise",
    "MultiplyHue",
    "MultiplyHueAndSaturation",
    "MultiplySaturation",
    "Noop",
    "OneOf",
    "OpticalDistortion",
    "Pad",
    "PadToAspectRatio",
    "PadToFixedSize",
    "PadToMultiplesOf",
    "PadToPowersOf",
    "PadToSquare",
    "Pepper",
    "PerspectiveTransform",
    "PiecewiseAffine",
    "Posterize",
    "Rain",
    "RainLayer",
    "RandAugment",
    "PosePreset",
    "RandomColorsBinaryImageColorizer",
    "RegularGridMaskGen",
    "RegularGridPointsSampler",
    "RegularGridVoronoi",
    "RelativeRegularGridPointsSampler",
    "RelativeRegularGridVoronoi",
    "RemoveCBAsByOutOfImageFraction",
    "RemoveSaturation",
    "ReplaceElementwise",
    "Resize",
    "Rot90",
    "Rotate",
    "Salt",
    "SaltAndPepper",
    "SaveDebugImageEveryNBatches",
    "Scale",
    "ScaleX",
    "ScaleY",
    "SegMapClassIdsMaskGen",
    "Sequential",
    "Sharpen",
    "ShearX",
    "ShearY",
    "SigmoidContrast",
    "Snowflakes",
    "SnowflakesLayer",
    "Solarize",
    "SomeColorsMaskGen",
    "SomeOf",
    "Sometimes",
    "StochasticParameterMaskGen",
    "SubsamplingPointsSampler",
    "Superpixels",
    "SuspiciousMultiImageShapeWarning",
    "SuspiciousSingleImageShapeWarning",
    "TotalDropout",
    "TranslateX",
    "TranslateY",
    "UniformColorQuantization",
    "UniformColorQuantizationToNBits",
    "UniformPointsSampler",
    "UniformVoronoi",
    "UnnormalizedBatch",
    "VerticalFlip",
    "VerticalLinearGradientMaskGen",
    "Voronoi",
    "WithBrightnessChannels",
    "WithChannels",
    "WithColorspace",
    "WithHueAndSaturation",
    "WithPolarWarping",
    "abstractmethod",
    "abstractproperty",
    "add_elementwise",
    "add_scalar",
    "add_scalar_",
    "adjust_contrast_gamma",
    "adjust_contrast_linear",
    "adjust_contrast_log",
    "adjust_contrast_sigmoid",
    "annotations",
    "apply_jigsaw",
    "apply_jigsaw_to_coords",
    "arithmetic",
    "artistic",
    "augm_utils",
    "base",
    "blend",
    "blend_alpha",
    "blend_alpha_",
    "blendlib",
    "blur",
    "blur_avg_",
    "blur_gaussian_",
    "blur_lib",
    "blur_mean_shift_",
    "change_color_temperature",
    "change_color_temperatures_",
    "change_colorspace_",
    "change_colorspaces_",
    "clip_augmented_image",
    "clip_augmented_image_",
    "clip_augmented_images",
    "clip_augmented_images_",
    "collections",
    "color",
    "color_lib",
    "colorlib",
    "compress_jpeg",
    "compute_croppings_to_reach_aspect_ratio",
    "compute_croppings_to_reach_multiples_of",
    "compute_croppings_to_reach_powers_of",
    "compute_paddings_to_reach_aspect_ratio",
    "compute_paddings_to_reach_multiples_of",
    "compute_paddings_to_reach_powers_of",
    "contrast",
    "convolutional",
    "convolve",
    "convolve_",
    "copy_arrays",
    "copy_module",
    "cutout",
    "cutout_",
    "cv2",
    "debug",
    "draw_debug_image",
    "edges",
    "estimate_max_number_of_channels",
    "flip",
    "fliplr",
    "flipud",
    "functools",
    "generate_jigsaw_destinations",
    "geometric",
    "handle_children_list",
    "ia",
    "iaa_convolutional",
    "iabase",
    "iadt",
    "iap",
    "iarandom",
    "imageio",
    "imgaug2",
    "imgcorruptlike",
    "invert",
    "invert_",
    "invert_reduce_to_nonempty",
    "itertools",
    "math",
    "meta",
    "multiply_elementwise",
    "multiply_elementwise_",
    "multiply_scalar",
    "multiply_scalar_",
    "ndimage",
    "np",
    "os",
    "pad",
    "pad_to_aspect_ratio",
    "pad_to_multiples_of",
    "pillike",
    "pooling",
    "posterize",
    "quantize_colors_kmeans",
    "quantize_colors_uniform",
    "quantize_kmeans",
    "quantize_uniform",
    "quantize_uniform_",
    "quantize_uniform_to_n_bits",
    "quantize_uniform_to_n_bits_",
    "re",
    "reduce_to_nonempty",
    "replace_elementwise_",
    "replace_segments_",
    "segment_voronoi",
    "segmentation",
    "shuffle_channels",
    "size",
    "size_lib",
    "sizelib",
    "ski_exposure",
    "skimage",
    "solarize",
    "solarize_",
    "stylize_cartoon",
    "tempfile",
    "tf",
    "weather",
    "FancyPCA",
    "FourierDomainAdaptation",
    "GlassBlur",
    "HEStain",
    "PlanckianJitter",
    "PlasmaBrightness",
    "PlasmaShadow",
    "ThinPlateSpline",
    "ZoomBlur",
    "cutmix",
    "mixup",
    "mosaic4",
]
